name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Install Qt
        shell: cmd
        run: |
          pip install aqtinstall
          python -m aqt install-qt windows desktop 6.2.2 win64_msvc2019_64
          echo "Qt6_DIR=D:\a\Daruma\Daruma\6.2.2\" >> $GITHUB_ENV
          echo "D:\a\Daruma\Daruma\6.2.2\bin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build
        shell: cmd
        env:
          vc_arch: x64
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          qmake
          nmake
          echo winSdkDir=%WindowsSdkDir% >> %GITHUB_ENV%
          echo winSdkVer=%WindowsSdkVersion% >> %GITHUB_ENV%
          echo vcToolsInstallDir=%VCToolsInstallDir% >> %GITHUB_ENV%
          echo vcToolsRedistDir=%VCToolsRedistDir% >> %GITHUB_ENV%
          mkdir build
          mv ./release/ImageEditor.exe ./build
          cd build
          windeployqt ImageEditor.exe
          cd ..
          zip portable.zip ./build/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            portable.zip
            
