name: Windows

on:
  push:
    tags:
      - "v*.*.*"
    
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Install Qt
        shell: pwsh
        run: |
          pip install aqtinstall
          python -m aqt install-qt --outputdir c:\Qt windows desktop 6.2.1 win64_mingw81 -m qtmultimedia
          python -m aqt list-tool windows desktop tools_ifw
          echo "QTDIR=c:\Qt\6.2.1\mingw81_64" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "c:\Qt\Tools\QtInstallerFramework\4.2\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "c:\Qt\6.2.1\mingw81_64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          Get-ChildItem -Recurse "c:\Qt\Tools" | Where { $_.PSIsContainer } | Select Name,FullName
